apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hrms-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashviniwe/hrms-gitops
    targetRevision: HEAD
    path: apps
    helm:
      releaseName: hrms
  destination:
    server: https://kubernetes.default.svc
    namespace: hrms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
